### ISSUE TITLE
SOLVED - wrong config files (llama 4bit:) RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:  Missing key(s) in state_dict: "model.layers.32.self_attn.q_proj.zeros" ...

### ISSUE THREAD

**Issue by BarfingLemurs** [ClayShoaf/oobabooga-one-click-bandaid#1]
I let the installer run, then ran bandaid.bat.

```
call conda install -y -c conda-forge cudatoolkit-dev

echo WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

call conda install -y pytorch torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit -c "nvidia/label/cuda-11.7.0" -c pytorch -c nvidia
```
It was interrupted after here because I clicked enter in my terminal, and that probably cancelled the model selecting.
I restarted the computer I then ran install.bat again, which overwrites this installations upgrade to torch 2.0, back to torch 1.13

flags: `call python server.py --cai-chat --gptq-bits 4 --gptq-model-type LLaMa --auto-devices --gptq-pre-layer 20`
models tried: 
- https://huggingface.co/decapoda-research/llama-7b-hf-int4 
- https://huggingface.co/nenkoru/alpaca-lora-7b-hf-int4

![image](https://user-images.githubusercontent.com/128182951/227729567-deb99b41-5eb4-47bb-a8f6-0d3b86121093.png)
![image](https://user-images.githubusercontent.com/128182951/227729616-19624c4f-5ed3-4c2b-a036-b0048e068372.png)

```
Starting the web UI...
The following models are available:

1. llama-7b
2. pygmalion-350m

Which one do you want to load? 1-2

1

Loading llama-7b...
Found models\llama-7b\llama-7b-4bit.pt
Loading model ...
Traceback (most recent call last):
  File "C:\Users\scfsi\Desktop\SD\one-click-installers-oobabooga-windows\text-generation-webui\server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\scfsi\Desktop\SD\one-click-installers-oobabooga-windows\text-generation-webui\modules\models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "C:\Users\scfsi\Desktop\SD\one-click-installers-oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 64, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits, shared.args.gptq_pre_layer)
  File "C:\Users\scfsi\Desktop\SD\one-click-installers-oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\llama_inference_offload.py", line 211, in load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "C:\Users\scfsi\Desktop\SD\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        Missing key(s) in state_dict: "model.layers.32.self_attn.q_proj.zeros", "model.layers.32.self_attn.q_proj.scales", "model.layers.32.self_attn.q_proj.bias", "model.layers.32.self_attn.q_proj.qweight", "model.layers.32.self_attn.k_proj.zeros", "model.layers.32.self_attn.k_proj.scales", "model.layers.32.self_attn.k_proj.bias", "model.layers.32.self_attn.k_proj.qweight", "model.layers.32.self_attn.v_proj.zeros", "model.layers.32.self_attn.v_proj.scales", "model.layers.32.self_attn.v_proj.bias", "model.layers.32.self_attn.v_proj.qweight", "model.layers.32.self_attn.o_proj.zeros", "model.layers.32.self_attn.o_proj.scales", "model.layers.32.self_attn.o_proj.bias", "model.layers.32.self_attn.o_proj.qweight", "model.layers.32.self_attn.rotary_emb.inv_freq", "model.layers.32.mlp.gate_proj.zeros", "model.layers.32.mlp.gate_proj.scales", "model.layers.32.mlp.gate_proj.bias", "model.layers.32.mlp.gate_proj.qweight", "model.layers.32.mlp.down_proj.zeros", "model.layers.32.mlp.down_proj.scales", "model.layers.32.mlp.down_proj.bias", "model.layers.32.mlp.down_proj.qweight", "model.layers.32.mlp.up_proj.zeros", "model.layers.32.mlp.up_proj.scales", "model.layers.32.mlp.up_proj.bias", "model.layers.32.mlp.up_proj.qweight", "model.layers.32.input_layernorm.weight", "model.layers.32.post_attention_layernorm.weight", "model.layers.33.self_attn.q_proj.zeros", "model.layers.33.self_attn.q_proj.scales", "model.layers.33.self_attn.q_proj.bias", "model.layers.33.self_attn.q_proj.qweight", "model.layers.33.self_attn.k_proj.zeros", "model.layers.33.self_attn.k_proj.scales", "model.layers.33.self_attn.k_proj.bias", "model.layers.33.self_attn.k_proj.qweight", "model.layers.33.self_attn.v_proj.zeros", "model.layers.33.self_attn.v_proj.scales", "model.layers.33.self_attn.v_proj.bias", "model.layers.33.self_attn.v_proj.qweight", "model.layers.33.self_attn.o_proj.zeros", "model.layers.33.self_attn.o_proj.scales", "model.layers.33.self_attn.o_proj.bias", "model.layers.33.self_attn.o_proj.qweight", "model.layers.33.self_attn.rotary_emb.inv_freq", "model.layers.33.mlp.gate_proj.zeros", "model.layers.33.mlp.gate_proj.scales", "model.layers.33.mlp.gate_proj.bias", "model.layers.33.mlp.gate_proj.qweight", "model.layers.33.mlp.down_proj.zeros", "model.layers.33.mlp.down_proj.scales", "model.layers.33.mlp.down_proj.bias", "model.layers.33.mlp.down_proj.qweight", "model.layers.33.mlp.up_proj.zeros", "model.layers.33.mlp.up_proj.scales", "model.layers.33.mlp.up_proj.bias", "model.layers.33.mlp.up_proj.qweight", "model.layers.33.input_layernorm.weight", "model.layers.33.post_attention_layernorm.weight", "model.layers.34.self_attn.q_proj.zeros", "model.layers.34.self_attn.q_proj.scales", "model.layers.34.self_attn.q_proj.bias", "model.layers.34.self_attn.q_proj.qweight", "model.layers.34.self_attn.k_proj.zeros", "model.layers.34.self_attn.k_proj.scales", "model.layers.34.self_attn.k_proj.bias", "model.layers.34.self_attn.k_proj.qweight", "model.layers.34.self_attn.v_proj.zeros", "model.layers.34.self_attn.v_proj.scales", "model.layers.34.self_attn.v_proj.bias", "model.layers.34.self_attn.v_proj.qweight", "model.layers.34.self_attn.o_proj.zeros", "model.layers.34.self_attn.o_proj.scales", "model.layers.34.self_attn.o_proj.bias", "model.layers.34.self_attn.o_proj.qweight", "model.layers.34.self_attn.rotary_emb.inv_freq", "model.layers.34.mlp.gate_proj.zeros", "model.layers.34.mlp.gate_proj.scales", "model.layers.34.mlp.gate_proj.bias", "model.layers.34.mlp.gate_proj.qweight", "model.layers.34.mlp.down_proj.zeros", "model.layers.34.mlp.down_proj.scales", "model.layers.34.mlp.down_proj.bias", "model.layers.34.mlp.down_proj.qweight", "model.layers.34.mlp.up_proj.zeros", "model.layers.34.mlp.up_proj.scales", "model.layers.34.mlp.up_proj.bias", "model.layers.34.mlp.up_proj.qweight", "model.layers.34.input_layernorm.weight", "model.layers.34.post_attention_layernorm.weight", "model.layers.35.self_attn.q_proj.zeros", "model.layers.35.self_attn.q_proj.scales", "model.layers.35.self_attn.q_proj.bias", "model.layers.35.self_attn.q_proj.qweight", "model.layers.35.self_attn.k_proj.zeros", "model.layers.35.self_attn.k_proj.scales", "model.layers.35.self_attn.k_proj.bias", "model.layers.35.self_attn.k_proj.qweight", "model.layers.35.self_attn.v_proj.zeros", "model.layers.35.self_attn.v_proj.scales", "model.layers.35.self_attn.v_proj.bias", "model.layers.35.self_attn.v_proj.qweight", "model.layers.35.self_attn.o_proj.zeros", "model.layers.35.self_attn.o_proj.scales", "model.layers.35.self_attn.o_proj.bias", "model.layers.35.self_attn.o_proj.qweight", "model.layers.35.self_attn.rotary_emb.inv_freq", "model.layers.35.mlp.gate_proj.zeros", "model.layers.35.mlp.gate_proj.scales", "model.layers.35.mlp.gate_proj.bias", "model.layers.35.mlp.gate_proj.qweight", "model.layers.35.mlp.down_proj.zeros", " ...
```

**Comment by ClayShoaf** [comment]
What happens if you remove `--gptq-pre-layer 20`?

**Comment by BarfingLemurs** [comment]
same big blob of text, when i run without --gptq-pre-layer 20 and / or remove auto-devices.

```
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        Missing key(s) in state_dict: "model.layers.32.self_attn.q_proj.zeros", "model.layers.32.self_attn.q_proj.scales", ...
```
any ideas on how to diagnose the issue? where did you get the .whl? (I foundit was https://github.com/oobabooga/text-generation-webui/issues/177#issuecomment-1464844721)
I'm on W11

hollow renamed folder with these  files: 
https://huggingface.co/nenkoru/alpaca-lora-7b-hf-int4/tree/main

the commit of gptq repository is 468c47c

maybe its something wrong with these converted pt models?

**Comment by BarfingLemurs** [comment]
nvm, I found the config and generation config hashes were different than the decopada-hf repo, I replaced them, and then it worked.

**Comment by winglian** [comment]
> nvm, I found the config and generation config hashes were different than the decopada-hf repo, I replaced them, and then it worked.

@BarfingLemurs which configs did you end up using to make it work? I'm having the same issue. thanks!

**Comment by BarfingLemurs** [comment]
@winglian the  config  and generation config file from https://huggingface.co/decapoda-research/llama-7b-hf/tree/main
